# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/jobplatform
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.cache=false

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.enabled=true

# ===============================
# OAuth2 - Google Login
# ===============================
spring.security.oauth2.client.registration.google.client-id=1059632741042-g39iiujvhu64s2ibl8nq17lqtkp4aeas.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email

server.error.whitelabel.enabled=false
server.error.include-message=always